import { Question } from '@/types';

export interface IELTSMockSection {
  id: string;
  title: string;
  part: 'reading' | 'listening' | 'writing' | 'speaking';
  timeAllowedMinutes: number;
  totalQuestions: number;
  instructions: string;
  questions: Question[];
}

export const QUESTION_BANK: Question[] = [
  // ==========================================
  // --- IELTS READING (All Question Types) ---
  // ==========================================
  {
    id: 'rd-1',
    skill: 'reading',
    title: 'Passage 1: Urbanization & Microclimates',
    passage: `Urbanization in developing nations has accelerated rapidly over the past three decades. While mega-cities offer unprecedented economic opportunities, municipal infrastructure often struggles to support population growth. Sustainable urban planning must balance high-density housing with green corridors to mitigate heat island effects and ensure clean water allocation. In addition, recent satellite imagery reveals that asphalt surfaces retain thermal energy late into the evening, elevating nocturnal ambient temperatures by up to 4.5 degrees Celsius compared to surrounding rural greenbelts.`,
    prompt: `What is the primary concern highlighted by the author regarding rapid urbanization?`,
    options: [
      'Lack of economic opportunities in mega-cities',
      'Strain on municipal infrastructure and resource allocation',
      'Over-expansion of rural agricultural land',
      'Decrease in nocturnal ambient temperatures'
    ],
    correctAnswer: 'Strain on municipal infrastructure and resource allocation',
    explanation: 'The passage explicitly states that "municipal infrastructure often struggles to support population growth" despite economic opportunities.',
    difficulty: 'Medium'
  },
  {
    id: 'rd-2',
    skill: 'reading',
    title: 'Passage 1: Vocabulary & Inference in Context',
    passage: `Renewable energy technologies have achieved grid parity in several major European markets. However, energy storage remains a critical bottleneck. Without scalable battery systems or green hydrogen alternatives, grid reliability during peak demand periods will require thermal backup generation.`,
    prompt: `What does the term "critical bottleneck" imply in the context of energy storage?`,
    options: [
      'A minor inconvenience easily solved by solar panels',
      'A primary obstacle limiting the full adoption and reliability of renewables',
      'A financial surplus generated by green hydrogen',
      'A physical valve in thermal power plants'
    ],
    correctAnswer: 'A primary obstacle limiting the full adoption and reliability of renewables',
    explanation: 'A bottleneck refers to a point of congestion or limiting factor. Here, lack of storage limits renewable grid reliability.',
    difficulty: 'Hard'
  },
  {
    id: 'rd-3',
    skill: 'reading',
    title: 'Passage 2: True / False / Not Given',
    passage: `Cognitive neuroscience suggests that multi-language acquisition enhances executive control processes in the prefrontal cortex. Studies demonstrate bilingual individuals switch between cognitive tasks faster than monolingual peers, regardless of socio-economic status.`,
    prompt: `According to the text, bilingual individuals always achieve higher academic test scores than monolinguals in all subjects.`,
    options: ['True', 'False', 'Not Given'],
    correctAnswer: 'Not Given',
    explanation: 'The text discusses faster cognitive task-switching, but makes no claim about overall academic test scores in all subjects.',
    difficulty: 'Medium'
  },
  {
    id: 'rd-4',
    skill: 'reading',
    title: 'Passage 2: Matching Headings & Main Idea',
    passage: `The preservation of ancient manuscripts presents a delicate dilemma for conservators. Exposure to ultraviolet light degrades cellulose fibers, while humid conditions encourage fungal growth. Modern archival facilities utilize nitrogen-purged glass enclosures maintained at constant temperature and humidity.`,
    prompt: `Which heading best summarizes this passage?`,
    options: [
      'Environmental Controls in Document Conservation',
      'The History of Ancient Cellulose Production',
      'Why Nitrogen Causes Fungal Growth in Paper',
      'The Financial Costs of Library Equipment'
    ],
    correctAnswer: 'Environmental Controls in Document Conservation',
    explanation: 'The passage highlights how light and humidity damage manuscripts and how modern archives use controlled nitrogen enclosures to preserve them.',
    difficulty: 'Hard'
  },

  // ============================================
  // --- IELTS LISTENING (Audio & Transcripts) ---
  // ============================================
  {
    id: 'ls-1',
    skill: 'listening',
    title: 'Section 1: Campus Accommodation Inquiry',
    audioUrl: '[Audio Script - Desk Officer]: Good morning! Welcome to the University Student Housing Office. How can I help you today? [Student]: Hi, I am inquiring about postgraduate single ensuite rooms for the Autumn semester starting in September. [Officer]: Standard ensuite rooms start at £145 per week including utility bills and internet access, while studio flats are £195 per week.',
    prompt: `What is the weekly cost of a standard postgraduate ensuite room including utilities?`,
    options: ['£125 per week', '£145 per week', '£195 per week', '£210 per week'],
    correctAnswer: '£145 per week',
    explanation: 'The accommodation officer explicitly states standard ensuite rooms are £145 per week including utility bills and internet.',
    difficulty: 'Easy'
  },
  {
    id: 'ls-2',
    skill: 'listening',
    title: 'Section 2: Campus Map & Venue Announcement',
    audioUrl: '[Audio Script - Professor Vance]: Attention all environmental science students! Next Thursday’s seminar on coastal erosion will take place in Seminar Room B in the Science Building, not Room A as printed on your original printed syllabus. Please ensure you bring your printed field data charts.',
    prompt: `Where will next Thursday’s coastal erosion seminar take place?`,
    options: ['Main Lecture Hall', 'Room A', 'Seminar Room B (Science Building)', 'Field Research Laboratory'],
    correctAnswer: 'Seminar Room B (Science Building)',
    explanation: 'The professor clarifies that the seminar location has been updated to Seminar Room B in the Science Building.',
    difficulty: 'Easy'
  },
  {
    id: 'ls-3',
    skill: 'listening',
    title: 'Section 3: Academic Consultation Feedback',
    audioUrl: '[Audio Script - Tutor]: Your argument regarding renewable integration is well-supported, but your literature review needs more recent peer-reviewed sources from 2022 onward rather than relying primarily on early 2000s studies.',
    prompt: `What specific academic improvement does the tutor recommend for the research paper?`,
    options: [
      'Shorten the introductory section',
      'Include recent peer-reviewed sources from 2022 onward',
      'Change the target citation format to Harvard style',
      'Remove all historical literature background'
    ],
    correctAnswer: 'Include recent peer-reviewed sources from 2022 onward',
    explanation: 'The tutor specifically requests more recent peer-reviewed sources from 2022 onward to strengthen the literature review.',
    difficulty: 'Medium'
  },
  {
    id: 'ls-4',
    skill: 'listening',
    title: 'Section 4: Lecture Monologue - Marine Biology',
    audioUrl: '[Audio Script - Lecturer]: Coral bleaching occurs when thermal stress forces corals to expel symbiotic algae known as zooxanthellae. Without these photosynthetic organisms, corals lose their vibrant coloration and vital energy source, leaving them vulnerable to disease.',
    prompt: `What photosynthetic organism is expelled during coral bleaching?`,
    options: ['Zooxanthellae algae', 'Phytoplankton', 'Bacterial cyanobacteria', 'Marine kelp'],
    correctAnswer: 'Zooxanthellae algae',
    explanation: 'The lecturer states that thermal stress causes corals to expel symbiotic algae known as zooxanthellae.',
    difficulty: 'Hard'
  },

  // =========================================
  // --- IELTS GRAMMAR & LEXICAL RESOURCE ---
  // =========================================
  {
    id: 'gm-1',
    skill: 'grammar',
    title: 'Complex Sentences - Third Conditionals',
    prompt: `Choose the grammatically correct option for Band 7+ complex sentence structure: "Had the research team _______ the calibration error earlier, the experiment results would have been valid."`,
    options: ['detected', 'detecting', 'detects', 'been detected'],
    correctAnswer: 'detected',
    explanation: 'Third conditional inverted structure: "Had [subject] + past participle [detected]".',
    difficulty: 'Hard'
  },
  {
    id: 'gm-2',
    skill: 'grammar',
    title: 'Subject-Verb Agreement in Formal Academic English',
    prompt: `Select the sentence with correct subject-verb agreement:`,
    options: [
      'Neither the professor nor the students was aware of the schedule change.',
      'Neither the professor nor the students were aware of the schedule change.',
      'Neither the professor or students has been aware of the schedule change.',
      'Neither the professors nor the student are aware of the schedule change.'
    ],
    correctAnswer: 'Neither the professor nor the students were aware of the schedule change.',
    explanation: 'With "neither... nor", the verb agrees with the subject closest to it ("the students" -> plural "were").',
    difficulty: 'Medium'
  },
  {
    id: 'gm-3',
    skill: 'grammar',
    title: 'Non-Restrictive Relative Clauses',
    prompt: `Which sentence correctly uses a non-restrictive relative clause with proper punctuation?`,
    options: [
      'The University of Melbourne which was founded in 1853 is Australia’s second oldest university.',
      'The University of Melbourne, which was founded in 1853, is Australia’s second oldest university.',
      'The University of Melbourne that was founded in 1853, is Australia’s second oldest university.',
      'The University of Melbourne, that was founded in 1853 is Australia’s second oldest university.'
    ],
    correctAnswer: 'The University of Melbourne, which was founded in 1853, is Australia’s second oldest university.',
    explanation: 'Non-restrictive relative clauses require commas around them and use "which" instead of "that".',
    difficulty: 'Medium'
  },

  // ========================================
  // --- IELTS VOCABULARY & COLLOCATIONS ---
  // ========================================
  {
    id: 'vb-1',
    skill: 'vocabulary',
    title: 'Academic Collocations (Band 7.5+)',
    prompt: `Which word best completes the high-level academic phrase: "To _______ a hypothesis based on empirical observation"?`,
    options: ['formulate', 'make', 'do', 'fabricate'],
    correctAnswer: 'formulate',
    explanation: 'In formal academic English, "formulate a hypothesis" is the standard Band 7+ collocation.',
    difficulty: 'Medium'
  },
  {
    id: 'vb-2',
    skill: 'vocabulary',
    title: 'Academic Tone Elevation',
    prompt: `Choose the most appropriate academic synonym for the underlined word: "The study *showed* a strong link between study habits and GPA."`,
    options: ['demonstrated', 'pointed out', 'got across', 'said'],
    correctAnswer: 'demonstrated',
    explanation: '"Demonstrated" elevates formal academic tone compared to conversational verbs.',
    difficulty: 'Easy'
  },
  {
    id: 'vb-3',
    skill: 'vocabulary',
    title: 'Precise Academic Terminology',
    prompt: `Select the word that means "having a profound, subtle, and detailed understanding":`,
    options: ['Nuanced', 'Superficial', 'Redundant', 'Ambiguous'],
    correctAnswer: 'Nuanced',
    explanation: '"Nuanced" describes subtle distinctions and deep comprehension in academic analysis.',
    difficulty: 'Medium'
  },

  // =============================================
  // --- IELTS WRITING (Task 1 & Task 2 Essays) ---
  // =============================================
  {
    id: 'wr-1',
    skill: 'writing',
    title: 'IELTS Writing Task 2 - Essay Prompt (250+ Words)',
    prompt: `Some people believe that international student exchange programs benefit students more than the host universities. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your knowledge or experience. (Write at least 250 words)`,
    explanation: 'Evaluated on Task Response, Coherence & Cohesion, Lexical Resource (vocabulary range), and Grammatical Range & Accuracy.',
    difficulty: 'Hard'
  },
  {
    id: 'wr-2',
    skill: 'writing',
    title: 'IELTS Writing Task 1 - Academic Data Report (150+ Words)',
    prompt: `The chart below shows the percentage of international students enrolled in higher education across four major destination countries (UK, USA, Canada, Australia) between 2015 and 2025. Summarise the information by selecting and reporting the main features, and make comparisons where relevant. (Write at least 150 words)`,
    explanation: 'Assessed on Task Achievement (selecting key trends without opinion), Coherence, Academic Vocabulary, and Complex Sentence Structures.',
    difficulty: 'Medium'
  },

  // ==============================================
  // --- IELTS SPEAKING (Part 1, Part 2, Part 3) ---
  // ==============================================
  {
    id: 'sp-1',
    skill: 'speaking',
    title: 'IELTS Speaking Part 1 - Personal & Academic Background',
    prompt: `Describe your current academic major or career path. What motivated you to choose this field, and how will earning a degree abroad advance your long-term ambitions? (Record or speak for 60 seconds)`,
    explanation: 'Focus on natural fluency, accurate sentence structures, clear pronunciation, and confident pacing without long pauses.',
    difficulty: 'Easy'
  },
  {
    id: 'sp-2',
    skill: 'speaking',
    title: 'IELTS Speaking Part 2 - Cue Card Topic Challenge',
    prompt: `Describe a challenging academic project or personal goal you successfully completed. You should say: what the project/goal was, what difficulties you encountered, how you overcame them, and why this achievement was meaningful to you. (1 min preparation, speak for 90–120 seconds)`,
    explanation: 'Evaluated on Fluency & Coherence, Lexical Resource, Grammatical Range & Accuracy, and Pronunciation.',
    difficulty: 'Medium'
  },
  {
    id: 'sp-3',
    skill: 'speaking',
    title: 'IELTS Speaking Part 3 - Deep Analytical Discussion',
    prompt: `How has international student mobility changed higher education globally in recent years? Do you think online remote learning will ever replace studying at physical overseas university campuses? (Speak for 90–120 seconds)`,
    explanation: 'Assessed on high-level analytical vocabulary, structured discourse markers, and complex argument construction.',
    difficulty: 'Hard'
  }
];

export const FULL_IELTS_MOCK_TEST: IELTSMockSection[] = [
  {
    id: 'mock-reading',
    title: 'IELTS Academic Reading Test',
    part: 'reading',
    timeAllowedMinutes: 60,
    totalQuestions: 4,
    instructions: 'Read the passages carefully and answer all questions within 60 minutes.',
    questions: QUESTION_BANK.filter(q => q.skill === 'reading')
  },
  {
    id: 'mock-listening',
    title: 'IELTS Listening Test',
    part: 'listening',
    timeAllowedMinutes: 30,
    totalQuestions: 4,
    instructions: 'Listen to the audio transcripts and select the best answer for each question.',
    questions: QUESTION_BANK.filter(q => q.skill === 'listening')
  },
  {
    id: 'mock-writing',
    title: 'IELTS Writing Test (Task 1 & Task 2)',
    part: 'writing',
    timeAllowedMinutes: 60,
    totalQuestions: 2,
    instructions: 'Complete both Task 1 (Data Report) and Task 2 (Essay Prompt). Ensure correct word length.',
    questions: QUESTION_BANK.filter(q => q.skill === 'writing')
  },
  {
    id: 'mock-speaking',
    title: 'IELTS Speaking Test (Part 1, 2 & 3)',
    part: 'speaking',
    timeAllowedMinutes: 14,
    totalQuestions: 3,
    instructions: 'Respond to Part 1, Part 2 (Cue Card), and Part 3 prompts with timed voice recording.',
    questions: QUESTION_BANK.filter(q => q.skill === 'speaking')
  }
];
